# -*- coding: utf-8 -*-
"""dbs_chatbot_transformer_08182025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NquZ7MNs5QVWJlVrriS03TU61tU6TSiU

***Transformer Version of the chatbot***

Below code provide the necessary installations required for the program to run and execute sucessfully. List of the installations is



*   sentence-transformers - library for pre-trained models for generating sentence embeddings
*   faiss-cpu - it ia a facebook AI library for fast similarity search
*   transformers - It is a hugging face library for transformer models like BERT, T5
*   accelerate - it is a utility for optimized training
*   bitsandbytes - 8/4 bit optimizers for large models.
*   nltk - NLP tools  for text processing tasks
*   bert-score - evaluation metric for comparing text similarity using BERT embeddings
"""

!pip install sentence-transformers faiss-cpu transformers accelerate bitsandbytes nltk bert-score

"""Below code imports the necessary libraries used throughout the project


*   os- for input/output operations like accessing local directory, file etc
*   SentenceTransformer- for semantics embeddings
*   faiss- for vectors similarity search
*   numpy-for numerical operations
*   T5ForConditionalGeneration- text-text generation tasks
*   T5Tokenizer- text-text generation tasks
*   AutoTokenizer- loaing casual language models
*   AutoModelForCausalLM-- loaing casual language models
*   pipeline-
*   nltk,nltk.download('punkt') - tokenizer word/sentence  
*   time - time operations
*   accuracy_score - evaluation metric
*   sentence_bleu - bleu score for text generation quality
*   SmoothingFunction - provide smoothing methods so that even if there is not a perfect match score is assigned based on partial match of text or semantic
*   bert_score  - to compute semantic similarity scores using bert embeddings.
*   json - json parsing etc
"""

import os
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from transformers import T5ForConditionalGeneration, T5Tokenizer
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from huggingface_hub import hf_hub_download, snapshot_download, login, HfApi, HfFolder, Repository
from google.colab import userdata
import nltk
import shutil
nltk.download('punkt')
# nltk.download('punkt_tab') # This download is not necessary and might cause issues
from transformers.modeling_utils import PreTrainedModel # Import PreTrainedModel explicitly

import time
from sklearn.metrics import accuracy_score
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from bert_score import score as bert_score
import json
import requests

"""Global Variables declaration"""

# Declaring global variables which are used throughout the program
mode_to_run = 'local'
save_to_hf_required = False
local_save_path = "/content/Saved_Model_Local"
local_hf_save_path = "/content/Saved_Model_HF"
repo_id = "sandeepkumar84/dbs-chatbot-transformer-hf-v3"
local_repo_path = "./dbs-chatbot-transformer-hf-v3" # define a local path for the repository

"""Innitial setup"""

# innitial setup required for the program
os.makedirs(local_save_path, exist_ok=True)
os.makedirs(local_hf_save_path, exist_ok=True)

git config --global user.email "sandeep.kumar_84@yahoo.co.in"
git config --global user.name "Sandeep Kumar"

"""#Part-1 Data Preprocessing and model training
**1.1 Data Collection**


"""

import os
import requests


github_urls_training = [
    "https://raw.githubusercontent.com/sandeepkumar-84/DBS/refs/heads/dbs_applied_research_project_v1/AppliedResearch/Working%20v1/Transformer%20Version/Transformer_Training_DataSet-1.txt",
    "https://raw.githubusercontent.com/sandeepkumar-84/DBS/refs/heads/dbs_applied_research_project_v1/AppliedResearch/Working%20v1/Transformer%20Version/Transformer_Training_DataSet-2.txt"
]

loaded = False

def load_from_github(urls):
    for url in urls:
        try:
            response = requests.get(url)
            if response.status_code == 200:
                content = response.text
                paras = [para.strip() for para in content.split('\n') if len(para.strip()) > 50]
                corpus_dbs.extend(paras)
                print(f"Loaded {len(paras)} paragraphs from Github: {url}")
            else:
                print(f"Failed to fetch {url} — Status code: {response.status_code}")
        except Exception as e:
            print(f"Error reading from GitHub file {url}: {e}")

corpus_dbs = []
folder_path_training = "/content/Research-Chatbot"


def get_from_local():
  for file_name in os.listdir(folder_path_training):
      file_path = os.path.join(folder_path_training, file_name)
      try:
          with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
              content = f.read()
              corpus_dbs.extend([para.strip() for para in content.split('\n') if len(para.strip()) > 50])
              loaded = True
              print(f"Loaded {len(corpus_dbs)} paragraphs from Local: {file_path}")
      except Exception as e:
          print(f"Error reading {file_path}: {e}")

get_from_local()

if not loaded:
    print("get data from github if not locally present..")
    load_from_github(github_urls_training)

print(f"Total paragraphs loaded into corpus_dbs: {len(corpus_dbs)}")

"""**1.2 Visualization**

below code plot the corpus as wordcloud
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt
text_data = " ".join(corpus_dbs)
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white',
    colormap='viridis'
).generate(text_data)


plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Corpus", fontsize=16)
plt.show()

"""**1.2 Load Required Models and Resources**

Load the pretrained sentence transformer model
used 'all-MiniLM-L6-v2' which is a lightweight, high-performance model for sentence embeddings. next code is to encode the corpus into dense vector embeddings and numpy array is returned while the progress is displayed during the process.

"""

model_dbs_transformer = SentenceTransformer('all-MiniLM-L6-v2')
corpus_embeddings_dbs = model_dbs_transformer.encode(corpus_dbs, show_progress_bar=True, convert_to_numpy=True)

"""Below section sets up the vector search engine"""

# fetching the dimensions of the embeddings
embedding_dim_transformer = corpus_embeddings_dbs.shape[1]
# creating a faiss index for similarity search
index_dbs = faiss.IndexFlatL2(embedding_dim_transformer)
# add the corpus embeddings to the FAISS index
index_dbs.add(corpus_embeddings_dbs)

print(f"FAISS index_dbs built with {index_dbs.ntotal} vectors.")

"""Saving the model,corpus, and indexes to local directory. Here in noteboob it is a notebook path. for python on local system it would be a local disk path"""

model_dbs_transformer.save(f"{local_save_path}/sentence_transformer")
faiss.write_index(index_dbs, f"{local_save_path}/faiss_index_dbs.index")
with open(f"{local_save_path}//corpus_dbs.json", "w") as f:
    json.dump(corpus_dbs, f)

"""Reloading the above locallys saved model, corpus and indexes"""



"""Belo code saves/deploys the model onto hugging face only if it is required(based on save_to_hf_required). In this case since it is already saved, the variable save_to_hf_required is set to false."""

hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)

#!git clone https://sandeepkumar84:HF_TOKEN@huggingface.co/sandeepkumar84/dbs-chatbot-transformer-hf-v3

def save_to_hugging_face_repo():
  api = HfApi()
  api.create_repo(repo_id, exist_ok=True)
  repo = Repository(local_dir=local_hf_save_path, clone_from=repo_id,use_auth_token=True)
  shutil.copytree(f"{local_save_path}/sentence_transformer",
                  f"{local_hf_save_path}/sentence_transformer",
                  dirs_exist_ok=True)

  shutil.copy(f"{local_save_path}/faiss_index_dbs.index", f"{local_hf_save_path}/faiss_index_dbs.index")
  shutil.copy(f"{local_save_path}/corpus_dbs.json", f"{local_hf_save_path}/corpus_dbs.json")

  repo.push_to_hub(commit_message="Initial checkpoint of DBS chatbot pipeline")

if save_to_hf_required == True:
  print("saving to hugging face..............")
  save_to_hugging_face_repo()

"""Below code retrieves it from hugging face"""

# declare variables

reloaded_model_local = None
reloaded_index_local = None
reloaded_corpus_local = None
reloaded_model_hf = None
reloaded_index_hf = None
reloaded_corpus_hf = None


def reload_local(local_save_path):
    global reloaded_model_local, reloaded_index_local, reloaded_corpus_local
    reloaded_model_local = SentenceTransformer(f"{local_save_path}/sentence_transformer")
    reloaded_index_local = faiss.read_index(f"{local_save_path}/faiss_index_dbs.index")
    with open(f"{local_save_path}/corpus_dbs.json","r",encoding="utf-8") as f:
        reloaded_corpus_local = json.load(f)
    print("Reloaded from LOCAL 😊")

def reload_hf(repo_id):
    global reloaded_model_hf, reloaded_index_hf, reloaded_corpus_hf
    local_repo_dir = snapshot_download(repo_id=repo_id)
    reloaded_model_hf  = SentenceTransformer(os.path.join(local_repo_dir,"sentence_transformer"))
    reloaded_index_hf  = faiss.read_index(os.path.join(local_repo_dir,"faiss_index_dbs.index"))
    with open(os.path.join(local_repo_dir,"corpus_dbs.json"),"r") as f:
        reloaded_corpus_hf = json.load(f)
    print("Reloaded from HUGGINGFACE ✅")

# ------------------------------------------------------------
# Automatically reload once based on mode_to_run
if mode_to_run=='local':
    reload_local(local_save_path)
elif mode_to_run=='hf':
    reload_hf(repo_id)

"""**1.3 Passage Retrieval**
below function selects top 3 similar passage from the corpus for a given query.
"""

'''
converts query into embedding, find distances between query and passages, then retrieve the actual text passage from corpus.
'''
def retrieve_passages(query, top_k=3):
    '''
    converts query into embedding, finds distances between query and passages,
    then retrieves the actual text passages from corpus.
    '''
    if mode_to_run == 'local' and reloaded_model_local is not None:
        model_dbs_transformer = reloaded_model_local
        index_dbs = reloaded_index_local
        corpus_dbs = reloaded_corpus_local
    elif mode_to_run == 'hf' and reloaded_model_local is not None:
        model_dbs_transformer = reloaded_model_hf
        index_dbs = reloaded_index_hf
        corpus_dbs = reloaded_corpus_hf
    else:
        model_dbs_transformer = model_dbs_transformer
        index_dbs = index_dbs
        corpus_dbs = corpus_embeddings_dbs

    query_embedding = model_dbs_transformer.encode([query], convert_to_numpy=True)
    distances, indices = index_dbs.search(query_embedding, top_k)
    results = [corpus_dbs[idx] for idx in indices[0]]
    return results

'''
converts query into embedding, find distances between query and passages, then retrieve the actual text passage from corpus.
'''
# Below code is the prior implementation for testing each different types of trained model. It is combined into one based on the selected mode.
'''
def retrieve_passages(query, top_k=3):
    query_embedding = model_dbs_transformer.encode([query], convert_to_numpy=True)
    distances, indices = index_dbs.search(query_embedding, top_k)
    results = [corpus_dbs[idx] for idx in indices[0]]
    return results

def retrieve_passages_reloaded_local(query, top_k=3):
    query_embedding_local = reloaded_model_local.encode([query], convert_to_numpy=True)
    distances, indices = reloaded_index_local.search(query_embedding_local, top_k)
    return [reloaded_corpus_local[idx] for idx in indices[0]]

def retrieve_passages_reloaded_hf(query, top_k=3):
    query_embedding_hf = reloaded_model_hf.encode([query], convert_to_numpy=True)
    distances, indices = reloaded_index_hf.search(query_embedding_hf, top_k)
    return [reloaded_corpus_hf[idx] for idx in indices[0]]

    '''

"""**1.4 Answer Generation Function (T5)**

below code generate an answer to a query using T5, customized on retrieved context passages.
"""

#load the pre-trained T5-base model & tokenizer for conditional text generation,
t5_model_dbs = T5ForConditionalGeneration.from_pretrained("t5-base")
t5_tokenizer_dbs = T5Tokenizer.from_pretrained("t5-base")

''' function first combine all retrieved context passages into a single string, format in question and context form
    , tokenize it and then generate answer out of t5 model. generated answer is decoded into human readable text and returned by function
'''
def generate_answer(query, context_passages):
    context = " ".join(context_passages)
    prompt = f"question: {query} context: {context}"
    inputs = t5_tokenizer_dbs(prompt, return_tensors="pt", truncation=True, padding=True)
    outputs = t5_model_dbs.generate(**inputs, max_length=128)
    answer = t5_tokenizer_dbs.decode(outputs[0], skip_special_tokens=True)
    return answer

"""belo code provide a sample interaction"""

query = "What are library opening hours?"
passages = retrieve_passages(query)

print("\nTop Retrieved Passages:")
for i, p in enumerate(passages):
    print(f"[{i+1}] {p}\n")

answer = generate_answer(query, passages)
print("Generated Answer:\n", answer)

# below code was to test independently each different type of reloaded versions of the models. It is not required since we can change mode variable and use above code.
'''
query = "What are library opening hours?"
passages = retrieve_passages(query,'local')

print("\nTop Retrieved Passages:")
for i, p in enumerate(passages):
    print(f"[{i+1}] {p}\n")

answer = generate_answer(query, passages)
print("Generated Answer:\n", answer)

query = "What are library opening hours?"
passages = retrieve_passages(query,'hf')

print("\nTop Retrieved Passages:")
for i, p in enumerate(passages):
    print(f"[{i+1}] {p}\n")

answer = generate_answer(query, passages)
print("Generated Answer:\n", answer)
'''

"""Sample implementatino of the chatbot using simple while loop.

"""

def start_chatbot(top_k=3):
    print(f"DBS Chatbot is ready Type 'exit' to quit.\n Running in mode = {mode_to_run}")

    while True:
        query = input("You: ")
        if query.lower() in ["exit", "quit"]:
            print("Goodbye!")
            break

        retrieved_passages = retrieve_passages(query)
        answer = generate_answer(query,retrieved_passages)

        print("DBS Chatbot:", answer)
        print("-" * 60)

"""Calling the chatbot function to start interaction"""

start_chatbot()

"""Since the above chatbot doesnt provide a noral conversation like incomoplete sentences and just provides specific answers. To make it more human like another model is used which is tiny llama"""

#setting the hugging face model id for the TinyLLaMA chat model into a a variable
model_id_tinyllm_dbs = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
# converting text to tokens
tokenizer_tinyllm_dbs = AutoTokenizer.from_pretrained(model_id_tinyllm_dbs)
# load the model
model_tinyllm_dbs = AutoModelForCausalLM.from_pretrained(model_id_tinyllm_dbs, device_map="auto", torch_dtype="auto")

"""below code uses TinyLLaMA to refine a raw model-generated answer into a friendly, conversational chatbot response."""

'''function uses a propmt which guides the style of the chat to the model '''
def refine_answer_llama(query, raw_answer):
    prompt = f"""<|system|>You are an intelligent chatbot. Your role is to convert the retreived chunks into humanized text..<|end|>
<|user|>Question: {query}
Answer: {raw_answer}
Convert the following text to a chatbot response. Add greetings and ask the user if they have any further questions. AT the end of the conversion, say Thank You.<|end|>
<|assistant|>"""

  # the prompt is tokenize
    inputs = tokenizer_tinyllm_dbs(prompt, return_tensors="pt").to(model_tinyllm_dbs.device)
  # generate the output
    outputs = model_tinyllm_dbs.generate(
        **inputs,
        max_new_tokens=500,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.8,
        pad_token_id=tokenizer_tinyllm_dbs.eos_token_id
    )

    # decode the generated tokens into text
    full_output = tokenizer_tinyllm_dbs.decode(outputs[0], skip_special_tokens=True)
    # extract only the the assistant's part from the response & outout is then returned
    if "<|assistant|>" in full_output:
        return full_output.split("<|assistant|>")[-1].strip()
    return full_output.strip()

"""Sample code to get the refined answer from the raw answer"""

# below code is just to tes the refined answer. Since due to limited scope of the work and time it is commented as it takes lot of time to generate the answer.
'''
query = "How many books does the DBS Library have?"
raw_answer = "over 43,000"

refined = refine_answer_llama(query, raw_answer)
print("📘 Refined Answer:", refined)
'''

"""Sample chatbot implementation"""

def start_chatbot_v2(top_k=3):
    print("DBS Chatbot is ready! Type 'exit' to quit.\n")

    while True:
        query = input("You: ")
        if query.lower() in ["exit", "quit"]:
            print("Goodbye!")
            break

        retrieved_passages = retrieve_passages(query)
        answer = generate_answer(query,retrieved_passages)
        print("DBS Chatbot original answer:", answer)
        print("-" * 60)

        refined_answer = refine_answer_llama(query, answer)

        # Step 5: Show the answer
        print("DBS Chatbot refined answer:", refined_answer)
        print("-" * 60)

"""chatbot execution"""

#start_chatbot_v2()

"""#Part-II Evaluation Pipeline

**1.5 Evaluation**

This section is focussed on the evaluation of the Transformer version of the DBS specific chatbot developed in the first part.
Evaluation is performed using function evaluate_transformer_model(). It evaluate the transformer model and contains all the different evaluation parameters required for the overall benchmarking

Evaluation Metrics used are :

Exact Match Accuracy → proportion of exact match of the response generated with the expected.

BLEU Score → n-gram overlap using NLTK with smoothing.

BERTScore-F1 → It gives semantic similarity using pretrained BERT embeddings.

Average Response Time → per-query inference time.

Sample test set
test_set = [
    {"query": "How many books DBS Library has?", "expected_answer": "over 43,000"},
     {"query": "Where can I access DBS WiFi?", "expected_answer": ""},
      {"query": "What are library opening hours?", "expected_answer": " 24 hours a day"},
       {"query": "What ratings did DBS earned?", "expected_answer": " 4 stars"},
        {"query": "how to view Library account?", "expected_answer": ""},
         {"query": "Are the Guides to Library resources for students with disabilities are also available in the Library?", "expected_answer": " on the library website"},
          {"query": "How many university partnerships does DBS has developed?", "expected_answer": " over 75"}
  ]

Load the tes set from the file. file could be at local directory in case of python code, it could be at the githib location or uploaded on the colab notebook.
"""

file_path_test = r"/content/Research-Chatbot/Transformer_Test_DataSet.json"

test_set = []

def load_test_set(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"The file {path} does not exist.")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

if __name__ == "__main__":
    try:
        test_set = load_test_set(file_path_test)
        print("Test set loaded successfully.")
        for item in test_set:
            print(f"Query: {item.get('query', '')}")
            print(f"Expected Answer: {item.get('expected_answer', '')}")
            print("-" * 50)
    except Exception as e:
        print(f"Error: {e}")

#test_set

'''
The function below evaluate the transformer model and contains all the different evaluation parameters required for the overall benchmarking

'''

# smoothing fn for to handle small or mismatched sequences
smoothie = SmoothingFunction().method4

def evaluate_transformer_model(test_set):
    # variable declaration
    results = []
    total_time = 0
    all_generated = []
    all_expected = []

    # for all the QnA pair in the test set
    for i, item in enumerate(test_set):
        query = item["query"]
        expected = item["expected_answer"]
        print(f"Evaluating Query {i+1}/{len(test_set)}")
        start_time = time.time() # to track the inference time
        retrieved_passages = retrieve_passages(query) # retrieve the passage from faiss
        generated = generate_answer(query,retrieved_passages) # generate the answer
        end_time = time.time()

        response_time = end_time - start_time
        total_time += response_time


        all_generated.append(generated)
        all_expected.append(expected)


        exact_match = int(expected.lower() in generated.lower())

        # generate bleu score
        reference = [expected.split()]
        candidate = generated.split()
        bleu = sentence_bleu(reference, candidate, smoothing_function=smoothie)

        results.append({
            "Query": query,
            "Generated": generated,
            "Expected": expected,
            "ExactMatch": exact_match,
            "BLEU": bleu,
            "TimeTaken": response_time
        })


    # generate bert score
    P, R, F1 = bert_score(all_generated, all_expected, lang="en", verbose=True)
    avg_bertscore_f1 = F1.mean().item()


    accuracy = sum(r["ExactMatch"] for r in results) / len(results)
    avg_bleu = sum(r["BLEU"] for r in results) / len(results)
    avg_time = total_time / len(results)

    print(f"\n--- Evaluation Summary ---")
    print(f"Accuracy (Exact Match): {accuracy:.2f}")
    print(f"Average BLEU Score: {avg_bleu:.2f}")
    print(f"Average BERTScore F1: {avg_bertscore_f1:.2f}")
    print(f"Average Inference Time: {avg_time:.2f} seconds\n")

    return results

"""**1.6 Output **

outputs the result.
"""

results = evaluate_transformer_model(test_set)
results